baseURL = "http://grahamannett.me/"
languageCode = "en-us"
title = "grahamannett"
copyright = "ðŸ¤§"

theme = "hugo-xmin"

[params]
    footer = "[contact me](mailto:graham.annett@gmail.com)"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "resume"
    url = "/resume/"
    weight = 3
[[menu.main]]
    name = "other"
    url = "/other/"
    weight = 10